baseurl: '/Wave-Function-Collapse' # the subpath of your site, e.g. /blog
url: 'https://CmndrSalamander.github.io' # the base hostname & protocol for your site, e.g. http://example.com
github_username: CmndrSalamander

permalink: /:collection/:year-:month-:day-:title:output_ext
show_excerpts: true

# Build settings
theme: minima
plugins:
  - jekyll-feed
