title: Wave Function Collapse Exploration
email: sidhant.roymoulik@gmail.com
baseurl: '/Wave-Function-Collapse' # the subpath of your site, e.g. /blog
url: 'https://Sidhant-Roymoulik.github.io' # the base hostname & protocol for your site, e.g. http://example.com
github_username: Sidhant-Roymoulik

permalink: /:collection/:year-:month-:day-:title:output_ext
show_excerpts: true

# Build settings
theme: hyde
plugins:
  - jekyll-feed
